"""add_unique_constraint_tenant_name

Revision ID: 7ec76ae3bec7
Revises: 53bc28a37225
Create Date: 2026-03-10 13:26:05.506787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec76ae3bec7'
down_revision: Union[str, Sequence[str], None] = '53bc28a37225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tenants', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    # ### end Alembic commands ###
